apiVersion: v2
name: heart-disease-api
description: A Helm chart for Heart Disease Prediction API
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - mlops
  - machine-learning
  - flask
  - api
maintainers:
  - name: MLOps Team
